FROM gcc:latest 
RUN apt-get -y update && apt-get install -y fortunes git cmake libev-dev iproute2 net-tools kmod 

# needed to build kernel
RUN apt-get install -y flex bison bc
#RUN apt install -y binutils flex bison util-linux kmod e2fsprogs jfsutils reiserfsprogs xfsprogs squashfs-tools btrfs-progs pcmciautils quota ppp nfs-kernel-server procps oprofile udev grub mcelog iptables openssl libcrypto bc
RUN apt install -y build-essential flex bison dwarves libssl-dev libelf-dev

COPY mys.sh ./

RUN git clone -b linux-msft-wsl-5.10.102.1 https://github.com/microsoft/WSL2-Linux-Kernel

# user's .config.
COPY .config WSL2-Linux-Kernel/

# NOTE! This .config can be generated by running:
#     cat /proc/config.gz | gunzip > .config
#     make prepare modules_prepare
#        ^---use the gui to enable can/vcan under Networking section

RUN cd WSL2-Linux-Kernel

WORKDIR WSL2-Linux-Kernel

#make modules (possibly not necessary[?])
RUN make modules
RUN make modules_install

# could rename the folder ot the original kernel, but I didn't have success here
# RUN mv /lib/modules/5.10.102.1-microsoft-standard-WSL2+/ /lib/modules/5.10.102.1-microsoft-standard-WSL2/

#make  kernel
RUN make -j8 
RUN make install

# user must then copy the kernel file [`vcan`] to their user base directory
